### ISSUE TITLE
Plugin configured, webhook set-up but is only posting to #general channel

### ISSUE THREAD

**Issue by carlvlewis** [discourse/discourse-slack-official#25]
Hi!

I've installed this plugin for our Discourse forum (http://forum.opensavannah.org) to push forum topics to the #opensavannah channel on Slack. I've configured this single channel as the one for the webhook to post to, and the channel itself recognizes that an incoming webhook has been installed on it.

But the posts are instead going to the default `#general` channel instead of the `#opensavannah` channel as specified in the Webhook set-up with Slack.

Has anyone else ran into this issue?

**Comment by mcwumbly** [comment]
> I've configured this single channel as the one for the webhook to post to

Did you do that in Slack or in Discourse?

Maybe the channel you choose in Slack is ignored (and perhaps that is a bug either in the code or in the documentation).

I'd recommend checking what you see as the Filter rules in Discourse under Admin > Plugins and then choose Slack on the left.

Those can be configured there or by slash commands in Slack.

**Comment by carlvlewis** [comment]
This issue was resolved thanks to @mcwumbly. Thanks!
