### ISSUE TITLE
Customize Icon

### ISSUE THREAD

**Issue by saschafoerster** [discourse/discourse-slack-official#7]
I would like to customize the icon for the bot. It seems as if it uses the Logo from Discourse, but I would prefer to use an icon-logo different from that. 
I tried to change it in Slack itself, but it seems to be overwritten.

**Comment by nicksahler** [comment]
I will add a sitesetting for this tonight!

**Comment by saschafoerster** [comment]
Great, thanks!

**Comment by nicksahler** [comment]
Added!

**Comment by saschafoerster** [comment]
How will the update arrive in my installation? Do I need to rebuild? Thanks!

**Comment by nicksahler** [comment]
If you are a hosted install it will update over time. If you host your own,
go to `/admin/upgrade` to update

**Comment by saschafoerster** [comment]
Great: it just works and now looks so much more beautiful!
