### ISSUE TITLE
Add link on subsequent post messages as well

### ISSUE THREAD

**Issue by bradleypriest** [discourse/discourse-slack-official#9]
Hi there, 
Is there a way to put the post link into every Slack message rather than just the first post on a topic?
It seems it's hard-coded that way, would you accept a PR changing it?

**Comment by nicksahler** [comment]
That is a bug that should be fixed in the latest version! Are you self
hosting? If so, can you go to /admin/upgrade and tell me what version you
see?

**Comment by bradleypriest** [comment]
Hi Nick, 
We have a hosted Discourse instance, and the plugin is v1.0.0, but the settings link actually links to your fork. https://github.com/nicksahler/discourse-slack-official

**Comment by tgxworld** [comment]
This has been fixed in 

https://github.com/discourse/discourse-slack-official/commit/d1d2d1c9966f339a33d543c5255a6d505da9878d

> but the settings link actually links to your fork. https://github.com/nicksahler/discourse-slack-official

Oops that was a mistake. Fixed in 

https://github.com/discourse/discourse-slack-official/commit/b148f4b7d489da521c306a61c2848ad502811ac7
